### ISSUE TITLE
Modify Makefile to allow DOCKER_HUB_ID to be overridden by env var

### ISSUE THREAD

**Issue by t-fine** [open-horizon-services/web-helloworld-python#7]
In the future we plan to have a more advanced CI/CD process and allowing the `DOCKER_HUB_ID` to be overridden by an environment variable will needed. 

We should change 
``` 
DOCKERHUB_ID:=ibmosquito
``` 
to the following
```
DOCKER_HUB_ID ?= ibmosquito
```

**Comment by joewxboy** [comment]
This ticket is still open.  After cloning the repo and running `make` in the folder, I get an error:

```
% make
docker build -t /"web-hello-python":"1.0.0" .
invalid argument "/web-hello-python:1.0.0" for "-t, --tag" flag: invalid reference format
See 'docker build --help'.
make: *** [build] Error 125
```

Scanning the Makefile, I see line 3 shows the variable `DOCKER_HUB_ID` but lines 16 and 22, 29, 35, 41 and so on still use `DOCKERHUB_ID`.

Please modify all of the other occurrences from `DOCKERHUB_ID` to `DOCKER_HUB_ID` to match.  The script is currently broken.
