### ISSUE TITLE
Add build/publish shield to READMEs

### ISSUE THREAD

**Issue by t-fine** [open-horizon-services/web-helloworld-python#8]
Once the `Makefile` for each service is "complete" (build, test, publish, etc.) we should add a shield to the README to note this so new developers/users can easily determine which services are consumable.

**Comment by julianchen215** [comment]
Hi @joewxboy, may you please assign this issue to me?

**Comment by joewxboy** [comment]
This README needs better information:

1. Front matter
2. Shields - license should match LICENSE file
3. Description
4. Prerequisites
5. Installation
6. Usage
7. Advanced Details
8. Authors - should match MAINTAINERS.md

See examples of good README.md files:

* https://github.com/open-horizon-services/service-node-red-hello-world/blob/main/README.md
* https://github.com/open-horizon-services/service-fledge/blob/main/README.md
* https://github.com/open-horizon-services/service-homeassistant/blob/main/README.md

**Comment by szeyan543** [comment]
Hi @joewxboy @t-fine , may you please assign this issue to me?

**Comment by t-fine** [comment]
@szeyan543 can do!
