### ISSUE TITLE
Create test harness 

### ISSUE THREAD

**Issue by t-fine** [open-horizon-services/web-helloworld-python#9]
Similar to the open-horizon/examples repo travis job: https://github.com/open-horizon/examples/blob/master/.travis.yml

add a test for this service

**Comment by joewxboy** [comment]
This will require adding at least two new Makefile targets: "test" and "test-all-arches".

See the following example for one way to do this: https://github.com/open-horizon/examples/blob/master/edge/services/helloworld/Makefile#L25
